name: Pull Request Workflow

  on: [push]

  jobs:
    build:
      name: Workflow
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: education/autograding@v1